# Generated by Django 5.0.14 on 2026-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companysettings",
            name="default_currency",
            field=models.CharField(
                default="PKR",
                help_text="ISO 4217 code, e.g. USD, PKR, EUR",
                max_length=3,
            ),
        ),
    ]
