# Generated by Django 5.0.14 on 2026-07-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_alter_companysettings_default_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="distributor_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="distributor_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="distributor_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="distributor_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="invoice_header_note",
            field=models.TextField(
                blank=True, default="Thank you for shopping with us!"
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="show_tax_on_receipt",
            field=models.BooleanField(default=True),
        ),
    ]
