# Generated by Django 5.0.14 on 2026-10-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bankrecords", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="logo_data",
            field=models.TextField(blank=True),
        ),
    ]
