# Generated by Django 5.0.14 on 2026-07-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="cnic",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pakistani CNIC, format 35202-1234567-1",
                max_length=15,
            ),
        ),
    ]
