# Generated by Django 5.0.14 on 2026-09-13 05:31

import apps.backups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backup",
            name="file",
            field=models.FileField(upload_to=apps.backups.models.backup_upload_path),
        ),
    ]
